### ISSUE TITLE
setting authorization levels at registeration

### ISSUE THREAD

**Issue by nimesha95** [nimesha95/Wheels-Hub#10]
i think setting up user level in registration field is a unwise thing. Any solutions?

**Comment by nimesha95** [comment]
@xXZang3tsuXx  @Kavinda-Seasath  @KumudiniPerera

**Comment by xXZang3tsuXx** [comment]
How about the traditional two seperate layers of users - Admin & General. Only Admin can revoke or provoke the user levels ?

**Comment by Kavinda-Seasath** [comment]
u mean normal users can reg using the registration page and insurance companies must be added to the system by the admin?

**Comment by nimesha95** [comment]
@kavinda yep, something like that.. i mean like do we really need to register the normal users?
