### ISSUE TITLE
URGENT!! REVAMP UI DESIGNS 

### ISSUE THREAD

**Issue by nimesha95** [nimesha95/Wheels-Hub#15]
LIKE SAID BEFORE, UI REVAMP IS **NEEDED** FOR PROJECT. CHOOSE A TEMPLATE AND BUILD ON IT

**Comment by xXZang3tsuXx** [comment]
Adapting this [Template](https://themewagon.com/themes/tournest-free-responsive-travel-website-template/) for UI revamping. 
@Kavinda-Seasath, @KumudiniPerera

**Comment by nimesha95** [comment]
looks nice.. but @xXZang3tsuXx  this is a single page template right?
